### ISSUE TITLE
Crash bug

### ISSUE THREAD

**Issue by Neppkun** [cyyynthia/message-translate#4]
So I found a bug which crashes the client if triggered.

## Explanation
If you don't have translation language selected (Language you speak) and try to translate a message, your Discord client crashes instantly.

## Reproduction Steps
Open Discord with Powercord
Open the translator plugin's settings
Select blank on "Language you speak" box
Translate a message

Also it broke my Powercord install.

**Comment by cyyynthia** [comment]
This plugin doesn't have a box labelled "Language you speak" and doesn't let you select a blank value.
